### ISSUE TITLE
Options for using Kaiken and Android's Navigation Graph 

### ISSUE THREAD

**Issue by chris-mitchell** [dropbox/kaiken#20]
Using Android's Navigation Graph requires you to specify a Container View for your Fragment.  This will be the parent of the Fragment, and must be a concrete class. 

See details at https://developer.android.com/guide/navigation/navigation-getting-started#add-navhostfragment

Since Kaiken only provides interfaces, @DYJParker  suggested implementing a `AuthAwareNavHostFragment` which extends `NavHostFragment` and implements `AuthAwareFragment`.    

Instead of having each user implement these, should Kaiken support this and offer it as a module?  I'd assume it would go into a `scoping-navgraph` module to avoid the unnecessary dependencies if the user doesn't need them.  I'd also assume we'd support all the interfaces for NavGraph here. 

Thoughts @DYJParker or @rallat?

**Comment by digitalbuddha** [comment]
Make sense to me. Verify what is needed for navhost and compose as well. Maybe there is a higher order abstraction that works for all

**Comment by DYJParker** [comment]
If the alternative is creating an additional module, might an ignore-list make more sense? If we replace https://github.com/dropbox/kaiken/blob/master/scoping/src/main/java/com/dropbox/kaiken/scoping/AuthAwareFragment.kt#L89 with something like
```
        var parentFragment = getParentFragment()
        
        while(parentFragment?.let { it::class } in SKIP_LIST ){
            parentFragment = parentFragment?.parentFragment
        }
```
we can just skip _over_ known-not-going-to-be-DependencyProviderResolver Fragments.

I don't know Compose well enough to be able to speak to that...

**Comment by rodgavila** [comment]
I vote for having it in a different module. Even if it's just a single class. 

Regarding the implementation, I think there's a couple of options:

1)
`AuthAwareNavHostFragment` -> In this case the entire `NavHostFragment` inherits the entire scope of its containing single `Activity` (whereas it is an `AuthRequiredActivity` or an `AuthOptionalActivity`).

2)
`Auth(Required|Optional)NavHostFragment` -> In this case the entire `NavHostFragment` is either user scoped or no auth scoped. 

3)
The `NavHostFragment` isn't scoped. It's up to the individual fragments to specify their scope. I'm personally doing this, but then again I only have like 10 fragments.

One thing to consider is how do we implement mixed scenarios (user and noauth), and navigation between them. Because if the `NavHostFragment` is scoped to a user, then, no "children" fragments can be `NoAuth`. Your parent fragment is forcing you to be `auth`. So if for example we wanted to navigate to a file preview. That `FilePreview` fragment would need to live under a different `NavHostFragment`, maybe even a different activity.

**Comment by digitalbuddha** [comment]
Cc @alexio

**Comment by chris-mitchell** [comment]
Sounds good! I'll take a look into option 2 and will try to get something together today for it.
