### ISSUE TITLE
non-lazily initialized UserScoped module?

### ISSUE THREAD

**Issue by eyousefi** [dropbox/kaiken#31]
I have a UserScoped service module that i need to initialize in the main onCreate as it is a critical component and requires certain bindings during onCreate (i.e. dependency on adding a Factory to WorkManager which must happen in onCreate).

With the current layout, if i want to init the module by accessing the UserScoped graph in onCreate, everything else in that graph will also get initialized which can lead to a longer onCreate start up. 

Is it possible to create an in-between ground among AppScope and UserScope, i.e. AppUserScope for services that are User scoped but require to live with the App's lifetime?
In this proposed hierarchy, AppUserScope would live in between the layers AppScope and UserScope, and AppUserScope can access AppScope only while UserScope can access everything. 

Addition of such a thing would make development of service modules much easier as certain components operate with business logic around the app's onCreate. UserScope currently suits UI development quite well, but lacks some functions to make service modules easy to work.

**Comment by rodgavila** [comment]
In the case of this module, if it's a User Service, when would it be initialized when a user is signed-in? Would you wait for the next time app is started to initialize it? And then when would it be teardown? 

The reason why the User Scope is closely tied to the lifecycle of the the user is to simplify the lifecycles. I'm worried that introducing a new lifecycle would make things a little bit too complex, but if there's really a scenario that's not covered we can considering adding it.

I haven't played too much with WorkManager, but I'm wondering why does the initialization have to happen on `App.onCreate`? Or is the reason that the registration needs to happen as soon as you initialize so that the serve is "active"? If the former, then it looks a solution would be to "touch" the service when user services is initializzed, I think that `OfflinesManager` might be implemented this way. There's an explicit `init()`. Then when User Services is created then `myService.init()` is called for all these service that need to be started as soon as the app start.

But I agree that currently there's no equivalent for `Teardownable` for initialization.

**Comment by eyousefi** [comment]
In my particular case, i'm rewriting the manual uploads module and reasons for wanting to not be lazily initialized are:

- WorkManager basically starts after onCreate so we need to register our work factory that initializes manual upload work so they are not dropped || basically being ready to serve
- We also want to check the queue (async) and schedule the uploader to run if there are outstanding items on app launch

The example you mentioned, OfflineFilesManager, is not a kaiken/UserScoped module and we initialize it directly so have the option of doing the touch. In my case, my module is currently written as a UserScoped module, how can I get a specific module from kaiken during start up without creating the entire UserScope graph so i can call an init? Or was your suggestion to not use UserScoping initialize manually?

Currently doing something like:
`    for (user in allUsers()) {
        val manualUploadDependencies =
            (dbappUserServicesProvider.provideUserServicesOf(user.id) as ManualUploadDependencies)
        manualUploadDependencies.uploadManager.onStart()
}`

but this leads to the entire UserScope graph being created during onCreate. 

I should also mention my module does not depend on any UserScoped feature either

**Comment by rodgavila** [comment]
Ah! I see, I see. Actually I just hit this case in a different project, for the exact same case, an Uploader that need to start as soon as the application starts. 

One thing that I want to mention is that the user scope graph is not entirely generated because the modules are scoped. When the modules are scoped then Dagger will automatically wrap the access of the dependencies in Providers, so the dependencies will be created on first access. Given that, then you can add an `initialize()` method to the definition of `DbappUserServices` and call it just after the component is created.

1) Add an initialize method to definition of your `UserServices`. For example: 
```
abstract  class DbappUserServices {

     abstract val uploadManager: UploadManager

     @Component.Factory
     fun create(
         ...
     ): DbappUserServices


     fun initialize() {
          uploadManager.init() // Init method could be empty it doesn't matter, but will be enough to touch the dependency
     } 
}
```

Then, on `UserServicesManager` (or wherever the services are created and assigned to a map, you'll need to call `init()` just after the creation.


```
class UserServicesManager {

     fun onUserAdded(userId: String) {
         val userServices = DaggerDbappUserServices.create(...)
         userServices.initialize()
         servicesMap[userId] = userServices.
     }
}
```

The result is that, the graph will still be initialized except for the services that you touch manually on initialization.


One thing that we might need to do at the framework level is change the definition of [UserServices](https://github.com/dropbox/kaiken/blob/e71e94ff835dca1b042ec0f54aadfb69d66bd223/scoping/src/main/java/com/dropbox/kaiken/scoping/UserServices.kt)  to add an `initialize()` method.

**Comment by eyousefi** [comment]
> One thing that I want to mention is that the user scope graph is not entirely generated because the modules are scoped. When the modules are scoped then Dagger will automatically wrap the access of the dependencies in Providers, so the dependencies will be created on first access. Given that, then you can add an initialize() method to the definition of DbappUserServices and call it just after the component is created.

This is great information to know, thank you for sharing. 
I wasn't able to make our DbappUserServices into an abstract class (anvil complains back using interfaces only) but i went with the casting for now as it accomplishes the task.

Closing this out for now. Thanks again for your help
